version: '3.7'

services:
  db:
    image: postgres:16
    env_file:
      - Back/.env
    ports:
      - "5432:5432"
    networks:
      - my-network

  flask:
    container_name: Mainapp
    build: Back
    command:
      bash -c "flask db upgrade && python app.py"
    restart: on-failure:10
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - my-network

  bot:
    container_name: TelegramBot
    build: Front
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network: