"""Initial migration

Revision ID: c0c8a69538cc
Revises: 12c61568d87c
Create Date: 2024-07-07 00:32:03.872474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c8a69538cc'
down_revision = '12c61568d87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=200), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('salaryFrom', sa.Integer(), nullable=False),
    sa.Column('salaryTo', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.String(length=350), nullable=False),
    sa.Column('responsibility', sa.String(length=350), nullable=False),
    sa.Column('alternate_url', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=70), nullable=True),
    sa.Column('timeDay', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Vacancy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vacancy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vacancy', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('employer', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('salaryFrom', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salaryTo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requirement', sa.VARCHAR(length=350), autoincrement=False, nullable=False),
    sa.Column('responsibility', sa.VARCHAR(length=350), autoincrement=False, nullable=False),
    sa.Column('alternate_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('timeDay', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Vacancy_pkey')
    )
    op.drop_table('Jobs')
    # ### end Alembic commands ###
